---
services:
  postgres:
    image: postgres:18
    ports:
      - "5433:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql
    environment:
      POSTGRES_USER: terraform_reg_user
      POSTGRES_PASSWORD: terraform_reg_password
      POSTGRES_DB: terraform_registry
    healthcheck:
      test:
        ["CMD-SHELL", "pg_isready -U terraform_reg_user -d terraform_registry"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: terraform-registry-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - ./devutils/pgadmin/servers/servers.json:/pgadmin4/servers.json
      - pgpassfile_data:/var/lib/pgadmin
    depends_on:
      - postgres

volumes:
  postgres_data_dev:
  pgpassfile_data:
  module_data:
